name: calulator_workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.16.0"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run run
      - name : Run App
        run: npm run run
        